### PR TITLE
Add support for multiple batteries

### PR DESCRIPTION
**Pull request by Olivia5k**

### CODE REVIEW

**Comment by Olivia5k** [comment]
Please make sure that this works with only one battery as well. Can't really test that, haha.

**Comment by n1ck3** [comment]
Will test this.. I run a machine with 1 battery. And one without (virtually). Interesting to see how much that breaks. :)

**Comment by Olivia5k** [comment]
Did it break? :>

**Comment by Olivia5k** [comment]
Sneak merge! Pls complain if it didn't work. <3

**Comment by n1ck3** [comment]
It seems to work for me with 0 batteries -- on my virtual machine) :) I will test at home as well.

**Pull request merged**
